### PR TITLE
test: adds tests for adding and modifying mfs hamt shards

### PR DESCRIPTION
**Pull request by achingbrain**
Requires ipfs/js-ipfs-mfs#46 to be released.

I couldn't find a way to enable sharding for go and js without putting some conditionals in the daemon config - have I missed something?

### CODE REVIEW

**Comment by alanshaw** [comment]
Any chance you can rebase this and get some 💚 CI @achingbrain?

**Comment by achingbrain** [comment]
I'm seeing some seemingly unrelated errors in CI:

```
No available transports to dial peer QmNWQHexj877kvgjoH1udyNmxEDcVyuxHBW5PhkzpF6c3Y!
```

**Comment by achingbrain** [comment]
Will probably need a rebase after ipfs/interop#68 goes in

**Comment by achingbrain** [comment]
It's mostly green?

**Comment by alanshaw** [comment]
Merging as test failures are unrelated.

**Pull request merged**
