### PR TITLE
Enable Circuit Relay Tests

### PR DESCRIPTION
**Pull request by diasdavid**
Follows up on #27

### CODE REVIEW

**Comment by alanshaw** [comment]
hmm `Error: version mismatch: expected v6, found v7` - is the workspace not being cleaned up properly?

**Comment by diasdavid** [comment]
@alanshaw the problem is described at https://github.com/ipfs/interop/pull/28/files#r202613340. Trying to finish #28 first so that the issues with relay are separate from just using go-ipfs latest in general.

**Comment by alanshaw** [comment]
Oh I see...

**Comment by diasdavid** [comment]
Circuit is not ready (after all..)

```
 circuit
    go-go-go
      ✓ connect (1059ms)
      ✓ send
    js-go-go
      3) connect
      4) send
    go-go-js
      5) connect
      6) send
    js-go-js
      7) "before all" hook
      8) "after all" hook
    go-js-go
      9) connect
      10) send
    js-js-go
      11) connect
```

**Comment by diasdavid** [comment]
@dryajov did you fix the issues with https://github.com/ipfs/interop/pull/27/commits/5345a1712933ae30a130aa57ea4295fcf4a5bc2a ?

**Comment by dryajov** [comment]
@diasdavid partially, the other issue is here - https://github.com/libp2p/go-libp2p-circuit/pull/42

**Comment by dryajov** [comment]
The issue in actually addressed here - https://github.com/libp2p/js-libp2p-circuit/pull/28 now.

**Comment by diasdavid** [comment]
@jacobheun can you look into https://github.com/libp2p/js-libp2p-circuit when you are back and do the releases?

**Comment by jacobheun** [comment]
Yes! I will run through the reviews and releases tomorrow.

**Comment by diasdavid** [comment]
Thank you @jacobheun 🎉

**Pull request merged**
