### PR TITLE
test: add tests for CID version agnostic add and cat

### PR DESCRIPTION
**Pull request by alanshaw**
Current status:

screenshot 2018-11-27 at 15 49 23

### CODE REVIEW

**Comment by kevina** [comment]
Can I have a high level summary of what this is testing for?

**Comment by achingbrain** [comment]
@kevina It's testing that after adding content to IPFS, we can take the returned v0 CID, convert it to a v1 CID and still retrieve the content between the different implementations.

**Comment by alanshaw** [comment]
> @kevina It's testing that after adding content to IPFS, we can take the returned v0 CID, convert it to a v1 CID and still retrieve the content between the different implementations.

...and vice versa (add with v1, cat with v0)

**Comment by daviddias** [comment]
@alanshaw mind rebasing master onto this PR?

**Comment by alanshaw** [comment]
Merged with https://github.com/ipfs/interop/pull/51

**Pull request closed without merging**
