### PR TITLE
[WIP] fix: circuit-go-rv1-go

### PR DESCRIPTION
**Pull request by lidel**
> This reuses https://github.com/ipfs/interop/pull/462 + add some debug configs

This PR is a sandbox to try to fix `circuit` `go-rv1-go` test that fails on CI:
- https://github.com/ipfs/interop/runs/8247118958?check_suite_focus=true#step:5:64
-  https://github.com/ipfs/interop/pull/493#issuecomment-1240381755

### CODE REVIEW

**Comment by SgtPooki** [comment]
It seems to hang on executing daemonFactory where importing ipfsd-ctl-wrapper is and there's zero info. That same code works in every other environment

**Comment by achingbrain** [comment]
I see this from both go instances in the go-rv1-go test:

```console
2022-09-09T14:33:52.431Z ipfsd-ctl:daemon:stderr 2022-09-09T14:33:52.420Z	ERROR	provider.queue	queue/queue.go:124	Failed to enqueue cid: leveldb: closed
```

**Comment by achingbrain** [comment]
The problem is that the relay daemon doesn't always start up.

This build passed - https://github.com/ipfs/interop/actions/runs/3024182787/attempts/1 - I restarted the build, no changes between and it failed: https://github.com/ipfs/interop/actions/runs/3024182787/attempts/2

Successful (notice `RelayV1 is running!`):

```
circuit
    v1
      go-rv1-go
Starting relayd_v1..
scripts/libp2p-relay-daemon -config scripts/relayd_v1.config.json -id scripts/relayd_v1.identity
Generating peer identity in scripts/relayd_v1.identity

I am 12D3KooWPtFNMUscrU8wwe4k9zRTVf6qEw3UKkbJGdHjnvBaBof7

Public Addresses:

	/ip4/127.0.0.1/tcp/14111/ws/p2p/12D3KooWPtFNMUscrU8wwe4k9zRTVf6qEw3UKkbJGdHjnvBaBof7

The pprof debug is disabled

Starting RelayV1...
RelayV1 is running!

2022-09-09T17:22:17.2[21](https://github.com/ipfs/interop/runs/8275349685?check_suite_focus=true#step:5:22)Z ipfsd-ctl:daemon:stdout generating ED[25](https://github.com/ipfs/interop/runs/8275349685?check_suite_focus=true#step:5:26)519 keypair...done
peer identity: 12D3KooWRpiGjgudF2jbNbY5XX1rBmFHrt9HirHnitZEVm2rk5Hz
initializing IPFS node at /tmp/go_ipfs_-do6[39](https://github.com/ipfs/interop/runs/8275349685?check_suite_focus=true#step:5:40)0RkPR7fKkfy5ilx
to get started, enter:
... more output
```

Failure (notice no `RelayV1 is running!`):

```
circuit
    v1
      go-rv1-go
Starting relayd_v1..
scripts/libp2p-relay-daemon -config scripts/relayd_v1.config.json -id scripts/relayd_v1.identity
20[22](https://github.com/ipfs/interop/runs/8275773530?check_suite_focus=true#step:5:23)-09-09T17:50:14.132Z ipfsd-ctl:daemon:stdout generating ED[25](https://github.com/ipfs/interop/runs/8275773530?check_suite_focus=true#step:5:26)519 keypair...done
peer identity: 12D3KooWNHmhF1tpQ93TfeSysgxTh5mZKcqWPoCBaJCkZQVfpC1G
initializing IPFS node at /tmp/go_ipfs_s8ADoSJFYlDhNKuDRcZEd
to get started, enter:
... more output
```

**Comment by SgtPooki** [comment]
Working test run with GOLOG_LOG_LEVEL: https://github.com/ipfs/interop/runs/8277122415?check_suite_focus=true
log output: [go-rv1-go.success.logarchive.zip](https://github.com/ipfs/interop/files/9538235/go-rv1-go.success.logarchive.zip)


Failed test run with GOLOG_LOG_LEVEL: https://github.com/ipfs/interop/runs/8277153592?check_suite_focus=true
log output: [go-rv1-go.fail.logarchive.zip](https://github.com/ipfs/interop/files/9538233/go-rv1-go.fail.logarchive.zip)

**Comment by SgtPooki** [comment]
The most interesting part seems to be the lines between 'REUSEPORT' and `RelayV1 is running`. In the successful run, there is a lot going on that is missing from the failed run. The *First two things* missing in the failed run is 
1. `Generating peer identity in scripts/relayd_v1.identity`
2. `rcmgr	go-libp2p-resource-manager@v0.5.1/limit.go:75	initializing new limiter with config ...`

--- 
What starts the "generating peer identity" log entry, and why is there no failure in the failed workflow?
What starts the "initializing new limiter with config" log entry, and why is there no failure in the failed workflow?

**Comment by SgtPooki** [comment]
Set `ACTIONS_RUNNER_DEBUG=true` & `ACTIONS_RUNNER_DEBUG=true` in [this repo's secrets](https://github.com/ipfs/interop/settings/secrets/actions) per https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging. re-running the node-test workflow: https://github.com/ipfs/interop/actions/runs/3024796231

**Comment by achingbrain** [comment]
This seems to be a combination of issues.

1. When the `Generating peer identity` message appears, the relay daemon [cannot find an identity file at the passed path so generates a new peer id](https://github.com/libp2p/go-libp2p-relay-daemon/blob/2c601f023941e047328f18816ff107b49cbba856/identity.go#L12-L21).  If that message does not appear, it means there was a file at the path we pass to the daemon.  For whatever reason the daemon fails to read the file and seems to hang.
2. The electron tests were [failing to start the relay daemon at all with](https://github.com/ipfs/interop/runs/8283073241?check_suite_focus=true) `(node:1811) UnhandledPromiseRejectionWarning: Error: spawn scripts/libp2p-relay-daemon ENOENT`

To fix 1 I've made relay daemon use a random temporary file for it's identity so it's guaranteed to create a new peer id on every run.

To fix 2 I've made the relay daemon setup script download the daemon binary on-demand, similar to how aegir downloads electron on-demand when it's first used.

I've applied these fixes to #462 which should hopefully start to look a bit more healthy now.

**Comment by lidel** [comment]
Thank you @achingbrain :heart:  I assume this PR is no longer useful – closing.
Let's continue in https://github.com/ipfs/interop/pull/462

**Pull request closed without merging**
