### PR TITLE
fix: tests using files

### PR DESCRIPTION
**Pull request by vasco-santos**
Currently, the tests which uses the `api.files` are breaking. This PR fixes that.

This solves the problems in CI for the following PR:

[ipfs/interop#39](https://github.com/ipfs/interop/pull/39)
[ipfs/interop#47](https://github.com/ipfs/interop/pull/47)

Needs: 

- [ ] New release of `js-ipfs`

### CODE REVIEW

**Comment by vasco-santos** [comment]
@alanshaw there are still some tests failing in browser. 

Basically, it is created a proc node, where the files API is wrapped by the `files` property, and consequently has a different signature than the remaining types of spawned daemons.

[ipfs/interop/test/utils/circuit.js#L33-L53](https://github.com/ipfs/interop/blob/master/test/utils/circuit.js#L33-L53)

**Comment by alanshaw** [comment]
Needs a new version of js-ipfs with the files API refactor....

**Comment by vasco-santos** [comment]
Thanks! That's true, I installed `js-ipfs#master` in here and everything is running with success. Added In the description of the PR that it needs the new release!

**Comment by alanshaw** [comment]
Needs object API updates

**Comment by achingbrain** [comment]
So much CI pain.  `exchange files cat file` seems to time out with > 134MB files on some platforms, some of the time.  Doesn't seem related to this PR, other it touches the file tests.

**Comment by achingbrain** [comment]
Unless it's `Uncaught AssertionError: expected [Error: socket hang up] to not exist` that is, or `Uncaught AssertionError: expected [Error: connect ECONNREFUSED 127.0.0.1:41569] to not exist`

Of course, everything passes locally 😉

**Comment by achingbrain** [comment]
..and now Jenkins Mac workers are out of space.

**Comment by alanshaw** [comment]
Merged with https://github.com/ipfs/interop/pull/51

**Pull request closed without merging**
