### PR TITLE
test: JS IPFS 0.34

### PR DESCRIPTION
**Pull request by alanshaw**
Merge of https://github.com/ipfs/interop/pull/48 and https://github.com/ipfs/interop/pull/46 for JS IPFS 0.34 release

### CODE REVIEW

**Comment by alanshaw** [comment]
@jacobheun @vasco-santos the tests in `exchange-files.js` will consistently hang for about 1-2 minutes on one (or more) of the tests when run locally. e.g.

```console
  exchange files
    ✓ connect go <-> js
    ✓ connect go <-> go2
    ✓ connect js <-> js2
    cat file
      ✓ go -> js: 1.02 kB (283ms)
      ✓ js -> go: 1.02 kB (184ms)
      ✓ js -> js2: 1.02 kB (451ms)
      ✓ go -> go2: 1.02 kB
      ✓ go -> js: 63.5 kB (249ms)
      ✓ js -> go: 63.5 kB (162ms)
      ✓ js -> js2: 63.5 kB (419ms)
      ✓ go -> go2: 63.5 kB
      ✓ go -> js: 65.5 kB (244ms)
      ✓ js -> go: 65.5 kB (152ms)
      ✓ js -> js2: 65.5 kB (57720ms)   <------- on this run it's this one, but it changes
      ✓ go -> go2: 65.5 kB
      ✓ go -> js: 524 kB (535ms)
      ✓ js -> go: 524 kB (418ms)
      ✓ js -> js2: 524 kB (842ms)
      ✓ go -> go2: 524 kB (40ms)
```

Removing the bootstrap nodes from the config ([done here in this PR](https://github.com/ipfs/interop/pull/51/commits/8f7d821c2cb07b5bf328f626e2a4b7faa0336cbd)) helps but I still got an "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" on one of the runs I did.

There's clearly a bug(s) here and what I'm most concerned about is that libp2p doesn't seem to be stable connecting to just tens of nodes - when the DHT comes that number is going to increase significantly so this really needs to be addressed soon!

It would be rad if you could verify you're seeing the same hanging behaviour by checking out this PR and reverting the [commit to remove the bootstrap nodes](https://github.com/ipfs/interop/pull/51/commits/8f7d821c2cb07b5bf328f626e2a4b7faa0336cbd).

**Comment by alanshaw** [comment]
Now blocked on "Error: No available transports to dial peer QmPBzrGKvhgpP6gGFU1fqmCE3CETzGZY4b5LzLhGwfDupc!" 😞

**Comment by jacobheun** [comment]
And only on linux browsers, bleh. I'll take a look.

**Comment by daviddias** [comment]
image

This is a great improvement since https://github.com/ipfs/interop/pull/44#issuecomment-435576034 \o/

**Comment by daviddias** [comment]
what's the status ?

**Comment by daviddias** [comment]
image

**Comment by daviddias** [comment]
I took a moment to help drive this to the finish line and now CI is looking like:

image

Windows simply fails (probably missing some config??)

image

As for Firefox running, I re-run multiple times and the circuit tests are always the ones that crap out

https://travis-ci.com/ipfs/interop/jobs/177364408#L602-L607

**Comment by alanshaw** [comment]
> As for Firefox running, I re-run multiple times and the circuit tests are always the ones that crap out

We never ran tests on firefox before - it might actually be a bug! I found (and fixed) one yesterday thanks to testing in Firefox! https://github.com/ipfs/js-ipfs-http-client/pull/943/commits/f8ffa2b303310940aab175bc1b83e25ff25059c0

**Comment by daviddias** [comment]
@alanshaw interesting! That might mean that there also more bugs in js-ipfs to prune out. Shall we merge this PR as is so that we get the latest testing running and revisit with a new version of js-ipfs and js-ipfs-http-client?

**Comment by alanshaw** [comment]
Yeah ok lets do it, this PR is 99% there. Lets fix up the other issues in another PR.

**Pull request merged**
